# Generated by Django 3.2.3 on 2021-11-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailcode',
            name='user',
        ),
        migrations.AddField(
            model_name='useremailcode',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useremailcode',
            name='username',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
